# Generated by Django 5.2.9 on 2026-02-16 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_account_untracked_by'),
        ('users', '0024_usersettings_default_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Selects the account by default when creating new transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Default account'),
        ),
    ]
