from django.urls import path
import apps.rules.views as views

urlpatterns = [
    path(
        "rules/",
        views.rules_index,
        name="rules_index",
    ),
    path(
        "rules/list/",
        views.rules_list,
        name="rules_list",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/view/",
        views.transaction_rule_view,
        name="transaction_rule_view",
    ),
    path(
        "rules/transaction/add/",
        views.transaction_rule_add,
        name="transaction_rule_add",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/edit/",
        views.transaction_rule_edit,
        name="transaction_rule_edit",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/toggle-active/",
        views.transaction_rule_toggle_activity,
        name="transaction_rule_toggle_activity",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/delete/",
        views.transaction_rule_delete,
        name="transaction_rule_delete",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/take-ownership/",
        views.transaction_rule_take_ownership,
        name="transaction_rule_take_ownership",
    ),
    path(
        "rules/transaction/<int:pk>/dry-run/created/",
        views.dry_run_rule_created,
        name="transaction_rule_dry_run_created",
    ),
    path(
        "rules/transaction/<int:pk>/dry-run/deleted/",
        views.dry_run_rule_deleted,
        name="transaction_rule_dry_run_deleted",
    ),
    path(
        "rules/transaction/<int:pk>/dry-run/updated/",
        views.dry_run_rule_updated,
        name="transaction_rule_dry_run_updated",
    ),
    path(
        "rules/transaction/<int:pk>/share/",
        views.transaction_rule_share,
        name="transaction_rule_share_settings",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/transaction-action/add/",
        views.transaction_rule_action_add,
        name="transaction_rule_action_add",
    ),
    path(
        "rules/transaction/transaction-action/<int:transaction_rule_action_id>/edit/",
        views.transaction_rule_action_edit,
        name="transaction_rule_action_edit",
    ),
    path(
        "rules/transaction/transaction-action/<int:transaction_rule_action_id>/delete/",
        views.transaction_rule_action_delete,
        name="transaction_rule_action_delete",
    ),
    path(
        "rules/transaction/<int:transaction_rule_id>/update-or-create-transaction-action/add/",
        views.update_or_create_transaction_rule_action_add,
        name="update_or_create_transaction_rule_action_add",
    ),
    path(
        "rules/transaction/update-or-create-transaction-action/<int:pk>/edit/",
        views.update_or_create_transaction_rule_action_edit,
        name="update_or_create_transaction_rule_action_edit",
    ),
    path(
        "rules/transaction/update-or-create-transaction-action/<int:pk>/delete/",
        views.update_or_create_transaction_rule_action_delete,
        name="update_or_create_transaction_rule_action_delete",
    ),
]
