# Generated by Django 5.2.4 on 2025-08-06 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_alter_transactioncategory_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='keep_at_most',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Keep at most'),
        ),
    ]
