# Generated by Django 5.2.4 on 2025-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0014_alter_currency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='Automatic'),
        ),
        migrations.AddField(
            model_name='exchangerateservice',
            name='singleton',
            field=models.BooleanField(default=False, help_text='Create one exchange rate and keep updating it. Avoids database clutter.', verbose_name='Single exchange rate'),
        ),
    ]
