# Generated by Django 5.2.4 on 2025-08-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0015_exchangerate_automatic_exchangerateservice_singleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='Auto'),
        ),
    ]
