# Generated by Django 5.2.5 on 2025-08-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0016_alter_exchangerate_automatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerateservice',
            name='service_type',
            field=models.CharField(choices=[('synth_finance', 'Synth Finance'), ('synth_finance_stock', 'Synth Finance Stock'), ('coingecko_free', 'CoinGecko (Demo/Free)'), ('coingecko_pro', 'CoinGecko (Pro)'), ('transitive', 'Transitive (Calculated from Existing Rates)'), ('frankfurter', 'Frankfurter')], max_length=255, verbose_name='Service Type'),
        ),
    ]
