# Generated by Django 5.2.5 on 2025-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0020_migrate_synth_finance_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerateservice',
            name='service_type',
            field=models.CharField(choices=[('coingecko_free', 'CoinGecko (Demo/Free)'), ('coingecko_pro', 'CoinGecko (Pro)'), ('transitive', 'Transitive (Calculated from Existing Rates)'), ('frankfurter', 'Frankfurter'), ('twelvedata', 'TwelveData'), ('twelvedatamarkets', 'TwelveData Markets')], max_length=255, verbose_name='Service Type'),
        ),
    ]
