# Generated by Django 5.2.5 on 2025-08-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0021_alter_exchangerateservice_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
