# Generated by Django 5.2.10 on 2026-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0022_currency_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerateservice',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
