# Generated by Django 5.2 on 2025-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0014_alter_transactionrule_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionruleaction",
            options={
                "ordering": ["order"],
                "verbose_name": "Edit transaction action",
                "verbose_name_plural": "Edit transaction actions",
            },
        ),
        migrations.AlterModelOptions(
            name="updateorcreatetransactionruleaction",
            options={
                "ordering": ["order"],
                "verbose_name": "Update or create transaction action",
                "verbose_name_plural": "Update or create transaction actions",
            },
        ),
        migrations.AddField(
            model_name="transactionruleaction",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AddField(
            model_name="updateorcreatetransactionruleaction",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
    ]
