# Generated by Django 5.2.5 on 2025-08-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_alter_transactionruleaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrule',
            name='sequenced',
            field=models.BooleanField(default=False, verbose_name='Sequenced'),
        ),
    ]
