# Generated by Django 5.2.5 on 2025-08-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_transactionrule_sequenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='search_mute',
            field=models.TextField(blank=True, verbose_name='Search Mute'),
        ),
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='search_mute_operator',
            field=models.CharField(choices=[('exact', 'is exactly'), ('contains', 'contains'), ('startswith', 'starts with'), ('endswith', 'ends with'), ('eq', 'equals'), ('gt', 'greater than'), ('lt', 'less than'), ('gte', 'greater than or equal'), ('lte', 'less than or equal')], default='exact', max_length=10, verbose_name='Mute Operator'),
        ),
        migrations.AddField(
            model_name='updateorcreatetransactionruleaction',
            name='set_mute',
            field=models.TextField(blank=True, verbose_name='Mute'),
        ),
        migrations.AlterField(
            model_name='transactionruleaction',
            name='field',
            field=models.CharField(choices=[('account', 'Account'), ('type', 'Type'), ('is_paid', 'Paid'), ('date', 'Date'), ('reference_date', 'Reference Date'), ('mute', 'Mute'), ('amount', 'Amount'), ('description', 'Description'), ('notes', 'Notes'), ('category', 'Category'), ('tags', 'Tags'), ('entities', 'Entities'), ('internal_nome', 'Internal Note'), ('internal_id', 'Internal ID')], max_length=50, verbose_name='Field'),
        ),
    ]
