# Generated by Django 5.2.5 on 2025-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_updateorcreatetransactionruleaction_search_mute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrule',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
