#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -f /tmp/migrations_complete

python manage.py migrate

# Create flag file to signal migrations are complete
touch /tmp/migrations_complete

python manage.py setup_users
python manage.py setup_oauth

exec python manage.py runserver 0.0.0.0:8000
