#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Remove flag file if it exists from previous run
rm -f /tmp/migrations_complete

python manage.py collectstatic --noinput
python manage.py migrate

# Create flag file to signal migrations are complete
touch /tmp/migrations_complete

python manage.py setup_users
python manage.py setup_oauth

exec gunicorn WYGIWYH.wsgi:application --bind 0.0.0.0:8000 --timeout 600
